#!/usr/bin/env python3
"""Write a tiny source-able environment file for Slurm array jobs.

Submitting with ``--export=ALL`` can fail on clusters where the user's login
environment is large.  This helper writes only the variables the array task
needs, so callers can submit with ``--export=NIL`` and pass the file path as an
argument to the array script.
"""

from __future__ import annotations

import argparse
import os
import shlex
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("assignments", nargs="*", metavar="KEY=VALUE")
    args = parser.parse_args()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by scripts/slurm/write_sbatch_env.py",
        "# Source this file from a Slurm array script submitted with --export=NIL.",
    ]
    for item in args.assignments:
        if "=" not in item:
            raise SystemExit(f"expected KEY=VALUE, got: {item}")
        key, value = item.split("=", 1)
        if not key or not key.replace("_", "").isalnum() or key[0].isdigit():
            raise SystemExit(f"invalid shell variable name: {key}")
        lines.append(f"export {key}={shlex.quote(value)}")

    tmp = args.output.with_suffix(args.output.suffix + f".tmp.{os.getpid()}")
    tmp.write_text("\n".join(lines) + "\n", encoding="utf-8")
    tmp.replace(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
